# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/borrwor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/borrwor.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13proto/borrwor.proto\"0\n\x0f\x42orrowerRequest\x12\n\n\x02Id\x18\x01 \x01(\x05\x12\x11\n\tn_account\x18\x02 \x01(\x05\"#\n\x10\x42orrowerResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"7\n\x16\x42\x61nkReturnCheckRequest\x12\n\n\x02Id\x18\x01 \x01(\x03\x12\x11\n\tn_account\x18\x02 \x01(\x03\"*\n\x17\x42\x61nkReturnCheckResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\";\n\x1a\x44\x65\x66\x65rredInstallmentRequest\x12\n\n\x02Id\x18\x01 \x01(\x03\x12\x11\n\tn_account\x18\x02 \x01(\x03\".\n\x1b\x44\x65\x66\x65rredInstallmentResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xd0\x01\n\x06\x42orrow\x12\x32\n\x0bRequestLoan\x12\x10.BorrowerRequest\x1a\x11.BorrowerResponse\x12\x41\n\x0cRequestCheck\x12\x17.BankReturnCheckRequest\x1a\x18.BankReturnCheckResponse\x12O\n\x12RequestInstallment\x12\x1b.DeferredInstallmentRequest\x1a\x1c.DeferredInstallmentResponseb\x06proto3'
)




_BORROWERREQUEST = _descriptor.Descriptor(
  name='BorrowerRequest',
  full_name='BorrowerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Id', full_name='BorrowerRequest.Id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='n_account', full_name='BorrowerRequest.n_account', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=71,
)


_BORROWERRESPONSE = _descriptor.Descriptor(
  name='BorrowerResponse',
  full_name='BorrowerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='BorrowerResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=108,
)


_BANKRETURNCHECKREQUEST = _descriptor.Descriptor(
  name='BankReturnCheckRequest',
  full_name='BankReturnCheckRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Id', full_name='BankReturnCheckRequest.Id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='n_account', full_name='BankReturnCheckRequest.n_account', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=165,
)


_BANKRETURNCHECKRESPONSE = _descriptor.Descriptor(
  name='BankReturnCheckResponse',
  full_name='BankReturnCheckResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='BankReturnCheckResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=209,
)


_DEFERREDINSTALLMENTREQUEST = _descriptor.Descriptor(
  name='DeferredInstallmentRequest',
  full_name='DeferredInstallmentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Id', full_name='DeferredInstallmentRequest.Id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='n_account', full_name='DeferredInstallmentRequest.n_account', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=270,
)


_DEFERREDINSTALLMENTRESPONSE = _descriptor.Descriptor(
  name='DeferredInstallmentResponse',
  full_name='DeferredInstallmentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='DeferredInstallmentResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=318,
)

DESCRIPTOR.message_types_by_name['BorrowerRequest'] = _BORROWERREQUEST
DESCRIPTOR.message_types_by_name['BorrowerResponse'] = _BORROWERRESPONSE
DESCRIPTOR.message_types_by_name['BankReturnCheckRequest'] = _BANKRETURNCHECKREQUEST
DESCRIPTOR.message_types_by_name['BankReturnCheckResponse'] = _BANKRETURNCHECKRESPONSE
DESCRIPTOR.message_types_by_name['DeferredInstallmentRequest'] = _DEFERREDINSTALLMENTREQUEST
DESCRIPTOR.message_types_by_name['DeferredInstallmentResponse'] = _DEFERREDINSTALLMENTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BorrowerRequest = _reflection.GeneratedProtocolMessageType('BorrowerRequest', (_message.Message,), {
  'DESCRIPTOR' : _BORROWERREQUEST,
  '__module__' : 'proto.borrwor_pb2'
  # @@protoc_insertion_point(class_scope:BorrowerRequest)
  })
_sym_db.RegisterMessage(BorrowerRequest)

BorrowerResponse = _reflection.GeneratedProtocolMessageType('BorrowerResponse', (_message.Message,), {
  'DESCRIPTOR' : _BORROWERRESPONSE,
  '__module__' : 'proto.borrwor_pb2'
  # @@protoc_insertion_point(class_scope:BorrowerResponse)
  })
_sym_db.RegisterMessage(BorrowerResponse)

BankReturnCheckRequest = _reflection.GeneratedProtocolMessageType('BankReturnCheckRequest', (_message.Message,), {
  'DESCRIPTOR' : _BANKRETURNCHECKREQUEST,
  '__module__' : 'proto.borrwor_pb2'
  # @@protoc_insertion_point(class_scope:BankReturnCheckRequest)
  })
_sym_db.RegisterMessage(BankReturnCheckRequest)

BankReturnCheckResponse = _reflection.GeneratedProtocolMessageType('BankReturnCheckResponse', (_message.Message,), {
  'DESCRIPTOR' : _BANKRETURNCHECKRESPONSE,
  '__module__' : 'proto.borrwor_pb2'
  # @@protoc_insertion_point(class_scope:BankReturnCheckResponse)
  })
_sym_db.RegisterMessage(BankReturnCheckResponse)

DeferredInstallmentRequest = _reflection.GeneratedProtocolMessageType('DeferredInstallmentRequest', (_message.Message,), {
  'DESCRIPTOR' : _DEFERREDINSTALLMENTREQUEST,
  '__module__' : 'proto.borrwor_pb2'
  # @@protoc_insertion_point(class_scope:DeferredInstallmentRequest)
  })
_sym_db.RegisterMessage(DeferredInstallmentRequest)

DeferredInstallmentResponse = _reflection.GeneratedProtocolMessageType('DeferredInstallmentResponse', (_message.Message,), {
  'DESCRIPTOR' : _DEFERREDINSTALLMENTRESPONSE,
  '__module__' : 'proto.borrwor_pb2'
  # @@protoc_insertion_point(class_scope:DeferredInstallmentResponse)
  })
_sym_db.RegisterMessage(DeferredInstallmentResponse)



_BORROW = _descriptor.ServiceDescriptor(
  name='Borrow',
  full_name='Borrow',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=321,
  serialized_end=529,
  methods=[
  _descriptor.MethodDescriptor(
    name='RequestLoan',
    full_name='Borrow.RequestLoan',
    index=0,
    containing_service=None,
    input_type=_BORROWERREQUEST,
    output_type=_BORROWERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RequestCheck',
    full_name='Borrow.RequestCheck',
    index=1,
    containing_service=None,
    input_type=_BANKRETURNCHECKREQUEST,
    output_type=_BANKRETURNCHECKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RequestInstallment',
    full_name='Borrow.RequestInstallment',
    index=2,
    containing_service=None,
    input_type=_DEFERREDINSTALLMENTREQUEST,
    output_type=_DEFERREDINSTALLMENTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BORROW)

DESCRIPTOR.services_by_name['Borrow'] = _BORROW

# @@protoc_insertion_point(module_scope)
