# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import borrwor_pb2 as proto_dot_borrwor__pb2


class BorrowStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestLoan = channel.unary_unary(
                '/Borrow/RequestLoan',
                request_serializer=proto_dot_borrwor__pb2.BorrowerRequest.SerializeToString,
                response_deserializer=proto_dot_borrwor__pb2.BorrowerResponse.FromString,
                )


class BorrowServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RequestLoan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BorrowServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestLoan': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestLoan,
                    request_deserializer=proto_dot_borrwor__pb2.BorrowerRequest.FromString,
                    response_serializer=proto_dot_borrwor__pb2.BorrowerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Borrow', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Borrow(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestLoan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Borrow/RequestLoan',
            proto_dot_borrwor__pb2.BorrowerRequest.SerializeToString,
            proto_dot_borrwor__pb2.BorrowerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
